import os
from contextlib import contextmanager
from pathlib import Path

from dotenv import load_dotenv
from psycopg import connect
from psycopg.rows import dict_row

PROJECT_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(PROJECT_ROOT / ".env")


def _get_database_url() -> str:
    database_url = os.getenv("INATOS_DATABASE_URL") or os.getenv("DATABASE_URL")
    if database_url is None or not database_url.strip():
        raise RuntimeError(
            "Missing required environment variable: INATOS_DATABASE_URL or DATABASE_URL"
        )

    return database_url.strip()


def init_database() -> None:
    with connect(_get_database_url(), row_factory=dict_row) as connection:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                username TEXT NOT NULL UNIQUE,
                full_name TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        connection.commit()


@contextmanager
def get_connection():
    connection = connect(_get_database_url(), row_factory=dict_row)

    try:
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()