# Lista de cargos possíveis para folha de pagamento

CARGOS_POSSIVEIS = [
    "MONITOR I",
    "PROFESSOR I",
    "AUXILIAR I",
    "COORDENADOR I",
    "COORDENADOR REGIONAL",
    "COORDENADOR TECNICO",
    "TEC. DE ENFERMAGEM I",
    "INTEGRADOR",
    "PROFESSOR(A) ED FISICA",
    "SUPERVISOR TECNICO",
    "EDUCADOR SOCIAL",
    "ASSIST. ADMINISTRATIVO",
    "TEC DE ENBFERMAGEM",
    "DIGITADOR",
    "DIRETOR TECNICO",
    "NUTRICIONISTA",
    "ENFERMEIRO",
    "INTEGRADOR ",
    "COORDENADOR(A) ADMINISTRATOR",
    "COORDENADOR(A) PEDAGOGICO",
    "PROFESSOR DE DANÇA"
]
